### ISSUE TITLE
Pupil Remote plugin errors

### ISSUE THREAD

**Issue by jedioli** [pupil-labs/pupil#100]
Hey! I've been trying out the pupil_remote.py plugin, and I found a few bugs (I believe).

On line 79, "g_pool.plugins:" is missing the "self." prefix.

Also, maybe this is a misunderstanding of 0MQ, but with the current code I can only send one message, with all later ones ignored. Doesn't 0MQ require both a send() and a recv() together? I added a short send() call at the end of update(), which seems to now allow for multiple messages. For example, a bool set by successfully receiving a message, then sending a short confirmation message if  the flag:

    def update(self,frame,events):
        rec_flag = False
        try:
            msg = self.socket.recv(flags=zmq.NOBLOCK)
        except zmq.ZMQError :
            msg = None
        if msg:
            rec_flag = True
            …

        if rec_flag:
            self.socket.send("msg received")
            rec_flag = False

**Comment by cpicanco** [comment]
(The pupil_remote.py update fn.)[https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/pupil_remote.py#L65]

**Comment by mkassner** [comment]
I fixed the typos: 64602fb973060f8fb9f0eeadf4e1d66b087c822e

When I wrote this plugin I was able to send messages as I needed. I will check again.

**Comment by mkassner** [comment]
Is this this a problem?

**Comment by jedioli** [comment]
Oops! I forgot to close the issue! However the last time I pulled from master (about a week ago) the send message bug was still a problem. I'll close the issue, but just contact me if you have any questions. Thanks for all the great development!!

**Comment by jedioli** [comment]
Thanks for fixing the send message bug! I noticed today one other problem: when sending only an 'R' command, without 'rec_name,' confirmation still tries to use self.g_pool.rec_name and throws an error, at https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/pupil_remote.py#L87. I believe it just needs to be indented once more? Accordingly, confirmation should have a case for 'R' without 'rec_name', instead of just sending 'Unknown error in receive logic.'

It's a minor issue, but my project needs all this to be automated. Thanks again for all the great work!
