### ISSUE TITLE
Surface tracker not working with new IPC interface

### ISSUE THREAD

**Issue by Tobias-Fischer** [pupil-labs/pupil#426]
Hi @mkassner,
The surface tracking is not working anymore since upgrading to Pupil 0.8. I guess it has not been updated to work with the new IPC stuff.
The traceback I get:
```
Process world:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/capture/world.py", line 428, in world
    p.update(frame,events)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/surface_tracker.py", line 212, in update
    events['surface'].append({'name':s.name,'uid':s.uid,'m_to_screen':s.m_to_screen.tolist(),'m_from_screen':s.m_from_screen.tolist(), 'timestamp':frame.timestamp,'camera_pose_3d':s.camera_pose_3d.tolist()})
AttributeError: 'NoneType' object has no attribute 'tolist'
```
Skimming through the source code, I guess several places are affected and need to be updated.

Thanks,
Tobias

**Comment by papr** [comment]
Should be fixed. Thanks for the report.

**Comment by Tobias-Fischer** [comment]
Hi @papr,
Thanks for the fix! However, it still doesn't work when 3D localization is enabled:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/robot/pupil/pupil/pupil_src/capture/world.py", line 428, in world
    p.update(frame,events)
  File "/home/tobias/robot/pupil/pupil/pupil_src/shared_modules/surface_tracker.py", line 212, in update
    events['surface'].append({'name':s.name,'uid':s.uid,'m_to_screen':s.m_to_screen.tolist(),'m_from_screen':s.m_from_screen.tolist(), 'timestamp':frame.timestamp,'camera_pose_3d':s.camera_pose_3d.tolist() if s.camera_pose_3d else None})
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
It would be great if you could have a look into that as well.

Thanks, Tobias

**Comment by papr** [comment]
My bad. Should have tested that. Thanks for catching it. :)

**Comment by Tobias-Fischer** [comment]
Thanks, working nicely :)
