### ISSUE TITLE
Manual Marker Calibration crashes Capture in Windows 0.8.7-w-19 bundle

### ISSUE THREAD

**Issue by ogik13** [pupil-labs/pupil#564]
As soon as the Calibration is started, the Capture freezes, and World Camera window stops responding. The eye cameras continue functioning. This forces me to close the Capture, and use a different calibration method - which is less efficient..

**Comment by willpatera** [comment]
@ogik13 - thanks for the bug report. We will investigate, fix, and re-release the bundle. We will update this issue when the bundle has been re-released.

**Comment by willpatera** [comment]
Hi @ogik13 - I have made some changes and re-bundled Pupil Capture for windows v0.8.7-w-20. Please [download](https://github.com/pupil-labs/pupil/releases/tag/v0.8.7-w#downloads) and test.

**Comment by ogik13** [comment]
Thanks Will,

I'll update tomorrow.

Cheers.

**Comment by StolzChris** [comment]
Hi guys, I've had the same problem with the previous version. Unfortunately, it did not change for me when testing the new version. There's still the bytearray convert exception when starting screen calibration (I prefer the manual one but I did not test it with the marker cards yet. However, the execution did not lead to a pupil capture crash).

I just updated Python to the mentioned 3.5.2 and OpenCV 3.1. Drivers work for me on Windows 7 Profess. SP 1. Here is the output when starting the capture software via cmd, trying to screen calibrate:

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS ver
sion.
['C:\\Users\\ouroboros\\Desktop\\pupil_capture_windows_os_v0.8.7-w-20\\Pupil Cap
ture\\pupil_capture.exe', '--multiprocessing-fork', 'parent_pid=8600', 'pipe_han
dle=788']
world - [DEBUG] plugin: Imported: <module 'pupil_lsl_relay' from 'C:\\Users\\our
oboros\\pupil_capture_settings\\plugins\\pupil_lsl_relay.py'>
world - [INFO] plugin: Added: <class 'pupil_lsl_relay.Pupil_LSL_Relay'>
world - [DEBUG] plugin: Scanning: pylsl
world - [DEBUG] plugin: Imported: <module 'pylsl' from 'C:\\Users\\ouroboros\\pu
pil_capture_settings\\plugins\\pylsl\\__init__.py'>
world - [DEBUG] uvc: Found device that mached uid:'2:6'
world - [DEBUG] uvc: Device '2:6' opended.
world - [DEBUG] uvc: avaible video modes: [{'rates': [30], 'size': (1920, 1080)}
, {'rates': [120, 90, 60, 30], 'size': (640, 480)}, {'rates': [60, 30], 'size':
(1280, 720)}, {'rates': [30], 'size': (1024, 768)}, {'rates': [60], 'size': (800
, 600)}, {'rates': [30], 'size': (1280, 1024)}, {'rates': [120], 'size': (320, 2
40)}]
world - [DEBUG] uvc: Adding "Auto Exposure Mode" control.
world - [DEBUG] uvc: Adding "Auto Exposure Priority" control.
world - [DEBUG] uvc: Adding "Absolute Exposure Time" control.
world - [DEBUG] uvc: Adding "Backlight Compensation" control.
world - [DEBUG] uvc: Adding "Brightness" control.
world - [DEBUG] uvc: Adding "Contrast" control.
world - [DEBUG] uvc: Adding "Gain" control.
world - [DEBUG] uvc: Adding "Power Line frequency" control.
world - [DEBUG] uvc: Adding "Hue" control.
world - [DEBUG] uvc: Adding "Saturation" control.
world - [DEBUG] uvc: Adding "Sharpness" control.
world - [DEBUG] uvc: Adding "Gamma" control.
world - [DEBUG] uvc: Adding "White Balance temperature" control.
world - [DEBUG] uvc: Adding "White Balance temperature,Auto" control.
world - [DEBUG] uvc: Setting mode: 1280,720,30
world - [DEBUG] plugin: Loading plugin: Log_Display with settings {}
world - [INFO] plugin: Loaded: Log_Display
world - [DEBUG] plugin: Loading plugin: Pupil_Remote with settings {'host': b'0.
0.0.0', 'use_primary_interface': True, 'port': b'50020'}
world - [WARNING] plugin: Plugin 'Pupil_Remote' failed to load from settings fil
e. Because of Error:can't concat bytes to str
world - [DEBUG] plugin: Loading plugin: Dummy_Gaze_Mapper with settings {}
world - [INFO] plugin: Loaded: Dummy_Gaze_Mapper
world - [DEBUG] plugin: Loading plugin: UVC_Manager with settings {'check_device
s': True}
world - [INFO] plugin: Loaded: UVC_Manager
world - [DEBUG] plugin: Loading plugin: Screen_Marker_Calibration with settings
{'fullscreen': True, 'marker_scale': 1.0}
world - [INFO] plugin: Loaded: Screen_Marker_Calibration
world - [DEBUG] plugin: Loading plugin: Display_Recent_Gaze with settings {}
world - [INFO] plugin: Loaded: Display_Recent_Gaze
world - [DEBUG] plugin: Loading plugin: Recorder with settings {'info_menu_conf'
: {}, 'rec_dir': 'C:\\Users\\ouroboros\\recordings', 'raw_jpeg': True, 'record_e
ye': False, 'user_info': {'name': '', 'additional_field': 'change_me'}, 'show_in
fo_menu': False, 'session_name': '2017_01_04', 'audio_src': 'No Audio'}
world - [INFO] plugin: Loaded: Recorder
world - [WARNING] world: Process started.
Estimated / selected altsetting bandwith : 904 / 1600.
world - [DEBUG] uvc: Stream start.
world - [WARNING] uvc: Turbojpeg jpeg2yuv: b'Premature end of JPEG file'
['C:\\Users\\ouroboros\\Desktop\\pupil_capture_windows_os_v0.8.7-w-20\\Pupil Cap
ture\\pupil_capture.exe', '--multiprocessing-fork', 'parent_pid=8600', 'pipe_han
dle=840']
['C:\\Users\\ouroboros\\Desktop\\pupil_capture_windows_os_v0.8.7-w-20\\Pupil Cap
ture\\pupil_capture.exe', '--multiprocessing-fork', 'parent_pid=8600', 'pipe_han
dle=848']
eye1 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 579 / 800.
eye0 - [WARNING] eye: Process started.
Estimated / selected altsetting bandwith : 579 / 800.
eye0 - [ERROR] uvc: Can't stop stream: Error:'Operation timed out.'. Will ignore
 this and try to continue.
eye1 - [ERROR] uvc: Can't stop stream: Error:'Operation timed out.'. Will ignore
 this and try to continue.
Estimated / selected altsetting bandwith : 579 / 800.
Estimated / selected altsetting bandwith : 579 / 800.
eye0 - [WARNING] uvc: Turbojpeg jpeg2yuv: b'Invalid SOS parameters for sequentia
l JPEG'
eye0 - [WARNING] uvc: Turbojpeg jpeg2yuv: b'Invalid SOS parameters for sequentia
l JPEG'
eye0 - [WARNING] uvc: Turbojpeg jpeg2yuv: b'Unsupported JPEG process: SOF type 0
xc6'
eye0 - [WARNING] uvc: Turbojpeg jpeg2yuv: b'Invalid SOS parameters for sequentia
l JPEG'
Estimated / selected altsetting bandwith : 579 / 800.
world - [INFO] plugin: Loaded: Fixation_Detector_3D

Starting Calibration
world - [INFO] calibration_routines.screen_marker_calibration: Starting Calibrat
ion
Process world:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "world.py", line 505, in world
  File "calibration_routines\screen_marker_calibration.py", line 307, in gl_disp
lay
  File "calibration_routines\screen_marker_calibration.py", line 338, in gl_disp
lay_in_window
  File "pyglui\cygl\utils.pyx", line 219, in pyglui.cygl.utils.draw_concentric_c
ircles (pyglui/cygl/utils.cpp:5384)
  File "pyglui\cygl\utils.pyx", line 280, in pyglui.cygl.utils.draw_concentric_c
ircles (pyglui/cygl/utils.cpp:4928)
  File "pyglui\cygl\shader.pyx", line 39, in pyglui.cygl.shader.Shader.__init__
(pyglui/cygl/shader.c:1902)
  File "pyglui\cygl\shader.pyx", line 92, in pyglui.cygl.shader.Shader._build_sh
ader (pyglui/cygl/shader.c:2341)
**TypeError: Can't convert 'bytearray' object to str implicitly**


The TypeError particular occurs together with the start of the calibration. Any idea?
The sound of the manual calibration works fine, I'll give it a try soon. Thank you very much!

Regards
Chris

**Comment by mkassner** [comment]
This error is now fixed but the underlying problem is with the OS/hardware. It does not support the version of OpenGL we require. Could you give some info of Hardware and OS setup?

**Comment by StolzChris** [comment]
Awesome! Anyway, the error still remains for my system. It's a Lenovo ThinkPad E530:
Intel Core i5-2450M CPU @ 2.50 GHz 2.50 GHz, 4 GB RAM, and it runs 64-bit Windows 7 Professional SP1. It has a NVIDIA GeForce GT 630M and an intern Intel HD Graphics 3000 chip. However, this is my personal computer, we just ordered a notebook with Windows 10 OS which is thought to run Pupil Labs.

**Comment by papr** [comment]
@StolzChris Please note that we do not support Windows 7. We target Windows 10. Please tell us, if the problems persist on the new Windows 10 notebook.

**Comment by adlinfakhriana** [comment]
![capture](https://cloud.githubusercontent.com/assets/24889527/21970964/0cb3d320-dbe7-11e6-964e-7216e8933176.PNG)
![2](https://cloud.githubusercontent.com/assets/24889527/21971077/2b1e0afa-dbe8-11e6-945f-2799c623428d.PNG)
![3](https://cloud.githubusercontent.com/assets/24889527/21971081/31a118b8-dbe8-11e6-9996-5df141a6e1d1.PNG)

hi, i'm having this kind of problem after reformatting my laptop and reinstall pupil labs. i got to know that the older version of the driver have bug that prevents libusb from accessing device. does it have anythng to do with my problem..? i'm a beginner, so i dont know very much about comp sorry fr any inconvenience

**Comment by willpatera** [comment]
Hi @adlinfakhriana - after reformatting the laptop you will have to reinstall drivers according to documentation here: https://github.com/pupil-labs/pupil/wiki/Windows-Driver-Setup

Please let us know if this solves your issues.

**Comment by adlinfakhriana** [comment]
![4](https://cloud.githubusercontent.com/assets/24889527/21971219/88cb8492-dbe9-11e6-9543-b79544919786.PNG)
yes, i've done it and reopen pupil capture

**Comment by willpatera** [comment]
@adlinfakhriana - can you please open `Task Manager` and see if there are other instances of Pupil Capture running in the background. If so, stop these processes and try running Pupil Capture again.

**Comment by adlinfakhriana** [comment]
![5](https://cloud.githubusercontent.com/assets/24889527/21971485/03e08946-dbec-11e6-96ee-d207e286408a.PNG)
microsoft skype cannot end task. and it still says already used or blocked

**Comment by willpatera** [comment]
@adlinfakhriana - I think the actual issue is the installation of drivers. Some users have reported that they used `Zadig` to *incorrectly* install `libusbK` drivers for **both** interface 0 and composite parents. Please uninstall all drivers for your cameras and follow steps in the [documentation here](https://github.com/pupil-labs/pupil/wiki/Windows-Driver-Setup).

@adlinfakhriana - If you are not able to proceed please open a **new issue** for further conversation so that we do not get too far off topic with this issue thread.

**Comment by adlinfakhriana** [comment]
so sorry for the late reply ive installed ubuntu anyway n everythng runs just great, thank u so much i really appreciate this ^^

**Comment by willpatera** [comment]
I am going to close this issue for the following reasons:

1. @StolzChris's issue is directly related to Windows 7 - and as @papr notes, Pupil for Windows is only officially supported on Windows 10. 
1. @adlinfakhriana's issue was likely related to the installation of drivers or Windows 10 auto-installing drivers for the composite parent and therefore camera being shown as `already in use` or `blocked`. Do not allow Windows to auto install drivers when connecting the Pupil headset for the first time. During auto-install it appears that Windows 10 installs drivers for the composite parent. The user may not notice Windows auto-install process and then proceed to install `libusbK` drivers with `Zadig` for cameras according to our [Windows driver installation docs](https://github.com/pupil-labs/pupil/wiki/Windows-Driver-Setup). However, the camera will still appear to be `in use` or `blocked`. To resolve this issue, you will need to uninstall the auto-installed drivers installed for the composite parent. You can uninstall drivers directly in the Windows `Device Manager`. Or, if unsure about which drivers are installed for the composite parent, you can install `libusbK` for composite parent and then delete drivers for all devices listed under the `libusbK` category. Unplug the headset and plug back in. Don't allow Windows to auto-install drivers, and then proceed with the steps in the Windows driver installation docs linked above. 
1. @ogik13 - has this issue been resolved for you? If not please leave a comment.

**Comment by ogik13** [comment]
Hey all,

Sorry for the delay in replying.

I have updated Capture and it seems to be working. I am unsure how well it is working, though. I am not sure what is happening during Manual Marker Calibration. Specifically, as soon as I show the Calibration Marker, I get a lot of beeps per 1 position, and messages like this:

world - [WARNING] calibration_routines.manual_marker_calibration: Marker moved too quickly: Aborted sample. Sampled 10 datapoints. Looking for steady marker again. 

This message pops up even if the marker is stationary, on the desk. 
Sometimes, this will result in : NO CONVERGENCE message. But sometimes it would state CONVERGENCE and it would be calibrated. However, not very accurate, even at the points where the calibration marker was held at. It would be off 2-5 cm.

Ogi

**Comment by willpatera** [comment]
Hi @ogik13 - thanks for the update. I will try to replicate your issue with manual marker calibration on the most recent windows build. Please feel free to open a separate issue for this.
