### ISSUE TITLE
Pupil Export : No valid dir supplied

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#643]
Hi there!
If I want to export a video I receive the following error:

Player [INFO] __main__ : Application Version: 0.9.0.17
Player [INFO] __main__ : System Info: User: root, Platform: Linux, Machine: belin, Release: 4.4.0-34-generic, Version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Player [INFO] plugin : Loaded: Trim_Marks
Player [INFO] plugin : Loaded: Seek_Bar
Player [INFO] plugin : Loaded: Log_Display
Player [INFO] plugin : Loaded: Vis_Scan_Path
Player [INFO] plugin : Loaded: Vis_Polyline
Player [INFO] plugin : Loaded: Vis_Circle
Player [INFO] plugin : Loaded: Video_Export_Launcher
Player [WARNING] plugin : Trim_Marks: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Seek_Bar: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Video_Export_Launcher: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Scan_Path: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Polyline: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Circle: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] __main__ : Previous export for range [0-328] already exsits - overwriting.
Player [ERROR] player_methods : No valid dir supplied
Player [ERROR] player_methods : No valid dir supplied

By pressing the export button or the 'E'-key a new instance of pupil_player opens.
The pupil_player window for selected export freezes.

The export dir should be valid since the recording could be created at the destination folder.
/home/testing/recordings 
ls command shows:
292404  4 drwxrwxr-x  3 user user 4096 Feb 23 11:48 recordings

I deleted pupil_player_settings before starting the pupil_player, so it was default.
The Issue also happens with BatchExporter.
I tested on two laptops (but nearly same configuration and ubuntu versions)

What is wrong? Do you need any further information?

![screenshot from 2017-02-23 11-43-31](https://cloud.githubusercontent.com/assets/10213803/23256565/42aac0fa-f9c0-11e6-904b-9c5d4725a56c.png)
mation?

Best regards

**Comment by mkassner** [comment]
We are about to release a bugfix version `v0.9.1` please try that once online tomorrow.

**Comment by fneitzel** [comment]
I see the sources of the bugfix v0.9.1 are released. Will you bundle it for Ubuntu today? Or do I need to work with sources and bundle myself?

**Comment by mkassner** [comment]
It s uploading....

**Comment by mkassner** [comment]
done!

**Comment by mkassner** [comment]
Let us know if this works now...

**Comment by fneitzel** [comment]
The issue still remains with latest version.

Player [WARNING] __main__ : You did not supply a data directory when you called this script!
Player [ERROR] player_methods : No valid dir supplied
Player [INFO] __main__ : Session setting are from older version of this app. I will not use those.
Player [INFO] player_methods : Updating meta info
Player [INFO] __main__ : Application Version: 0.9.1.7
Player [INFO] __main__ : System Info: User: testing, Platform: Linux, Machine: belin, Release: 4.4.0-34-generic, Version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Player [INFO] plugin : Loaded: Trim_Marks
Player [INFO] plugin : Loaded: Seek_Bar
Player [INFO] plugin : Loaded: Log_Display
Player [INFO] plugin : Loaded: Vis_Scan_Path
Player [INFO] plugin : Loaded: Vis_Polyline
Player [INFO] plugin : Loaded: Vis_Circle
Player [INFO] plugin : Loaded: Video_Export_Launcher
Player [WARNING] plugin : Trim_Marks: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Seek_Bar: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Video_Export_Launcher: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Scan_Path: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Polyline: Update will be deprecated soon. Use 'recent_events instead.'
Player [WARNING] plugin : Vis_Circle: Update will be deprecated soon. Use 'recent_events instead.'
Player [INFO] __main__ : Created export dir at "/home/testing/recordings/2017_02_24/000/exports/0-170"
Player [ERROR] player_methods : No valid dir supplied
Player [ERROR] player_methods : No valid dir supplied

**Comment by mkassner** [comment]
Alright. I m pretty sure I foxed this just now. I have replaced the app bundle for linux in the latest release. Please download and try again.

**Comment by fneitzel** [comment]
The export works! 
Thank you!
